# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_kalah_window(object):
    def setupUi(self, kalah_window):
        kalah_window.setObjectName("kalah_window")
        kalah_window.resize(688, 335)
        self.board = QtWidgets.QGraphicsView(kalah_window)
        self.board.setGeometry(QtCore.QRect(20, 43, 537, 243))
        self.board.setViewportUpdateMode(QtWidgets.QGraphicsView.FullViewportUpdate)
        self.board.setObjectName("board")
        self.active_player = QtWidgets.QLabel(kalah_window)
        self.active_player.setGeometry(QtCore.QRect(30, 13, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.active_player.setFont(font)
        self.active_player.setScaledContents(True)
        self.active_player.setObjectName("active_player")
        self.time_left = QtWidgets.QLabel(kalah_window)
        self.time_left.setGeometry(QtCore.QRect(400, 13, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.time_left.setFont(font)
        self.time_left.setScaledContents(True)
        self.time_left.setObjectName("time_left")
        self.layoutWidget = QtWidgets.QWidget(kalah_window)
        self.layoutWidget.setGeometry(QtCore.QRect(570, 43, 111, 182))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.newgame = QtWidgets.QPushButton(self.layoutWidget)
        self.newgame.setObjectName("newgame")
        self.verticalLayout.addWidget(self.newgame)
        self.stopgame = QtWidgets.QPushButton(self.layoutWidget)
        self.stopgame.setEnabled(False)
        self.stopgame.setObjectName("stopgame")
        self.verticalLayout.addWidget(self.stopgame)
        self.savegame = QtWidgets.QPushButton(self.layoutWidget)
        self.savegame.setEnabled(False)
        self.savegame.setObjectName("savegame")
        self.verticalLayout.addWidget(self.savegame)
        self.loadgame = QtWidgets.QPushButton(self.layoutWidget)
        self.loadgame.setObjectName("loadgame")
        self.verticalLayout.addWidget(self.loadgame)
        self.history = QtWidgets.QPushButton(self.layoutWidget)
        self.history.setObjectName("history")
        self.verticalLayout.addWidget(self.history)
        self.options = QtWidgets.QPushButton(self.layoutWidget)
        self.options.setObjectName("options")
        self.verticalLayout.addWidget(self.options)
        self.layoutWidget1 = QtWidgets.QWidget(kalah_window)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 300, 171, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.undo = QtWidgets.QPushButton(self.layoutWidget1)
        self.undo.setEnabled(False)
        self.undo.setObjectName("undo")
        self.horizontalLayout.addWidget(self.undo)
        self.advice = QtWidgets.QPushButton(self.layoutWidget1)
        self.advice.setObjectName("advice")
        self.horizontalLayout.addWidget(self.advice)

        self.retranslateUi(kalah_window)
        QtCore.QMetaObject.connectSlotsByName(kalah_window)

    def retranslateUi(self, kalah_window):
        kalah_window.setWindowTitle(QtCore.QCoreApplication.translate("kalah_window", "KALAH Gameboard", None))
        self.active_player.setText(QtCore.QCoreApplication.translate("kalah_window", "Player 1 moves", None))
        self.time_left.setText(QtCore.QCoreApplication.translate("kalah_window", "Time left: 00:00", None))
        self.newgame.setText(QtCore.QCoreApplication.translate("kalah_window", "New Game", None))
        self.stopgame.setText(QtCore.QCoreApplication.translate("kalah_window", "Stop Game", None))
        self.savegame.setText(QtCore.QCoreApplication.translate("kalah_window", "Save Game", None))
        self.loadgame.setText(QtCore.QCoreApplication.translate("kalah_window", "Load Game", None))
        self.history.setText(QtCore.QCoreApplication.translate("kalah_window", "History", None))
        self.options.setText(QtCore.QCoreApplication.translate("kalah_window", "Options", None))
        self.undo.setText(QtCore.QCoreApplication.translate("kalah_window", "Undo move", None))
        self.advice.setText(QtCore.QCoreApplication.translate("kalah_window", "Make an advice", None))

