# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_kalah_options(object):
    def setupUi(self, kalah_options):
        kalah_options.setObjectName("kalah_options")
        kalah_options.resize(238, 362)
        kalah_options.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(kalah_options)
        self.buttonBox.setGeometry(QtCore.QRect(-140, 320, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gameplay_box = QtWidgets.QGroupBox(kalah_options)
        self.gameplay_box.setGeometry(QtCore.QRect(10, 10, 221, 151))
        self.gameplay_box.setObjectName("gameplay_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gameplay_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.gameplay_box)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.ai_level_2 = QtWidgets.QSlider(self.gameplay_box)
        self.ai_level_2.setMinimum(1)
        self.ai_level_2.setMaximum(5)
        self.ai_level_2.setPageStep(1)
        self.ai_level_2.setProperty("value", 3)
        self.ai_level_2.setOrientation(QtCore.Qt.Horizontal)
        self.ai_level_2.setObjectName("ai_level_2")
        self.gridLayout_3.addWidget(self.ai_level_2, 4, 2, 1, 1)
        self.player_1 = QtWidgets.QComboBox(self.gameplay_box)
        self.player_1.setObjectName("player_1")
        self.gridLayout_3.addWidget(self.player_1, 1, 2, 1, 1)
        self.ai_level_1 = QtWidgets.QSlider(self.gameplay_box)
        self.ai_level_1.setMinimum(1)
        self.ai_level_1.setMaximum(5)
        self.ai_level_1.setPageStep(1)
        self.ai_level_1.setProperty("value", 3)
        self.ai_level_1.setOrientation(QtCore.Qt.Horizontal)
        self.ai_level_1.setObjectName("ai_level_1")
        self.gridLayout_3.addWidget(self.ai_level_1, 2, 2, 1, 1)
        self.ai_level_label_2 = QtWidgets.QLabel(self.gameplay_box)
        self.ai_level_label_2.setObjectName("ai_level_label_2")
        self.gridLayout_3.addWidget(self.ai_level_label_2, 4, 0, 1, 1)
        self.player_2 = QtWidgets.QComboBox(self.gameplay_box)
        self.player_2.setObjectName("player_2")
        self.gridLayout_3.addWidget(self.player_2, 3, 2, 1, 1)
        self.ai_level_label_1 = QtWidgets.QLabel(self.gameplay_box)
        self.ai_level_label_1.setObjectName("ai_level_label_1")
        self.gridLayout_3.addWidget(self.ai_level_label_1, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gameplay_box)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gameplay_box)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.stones = QtWidgets.QSpinBox(self.gameplay_box)
        self.stones.setMinimumSize(QtCore.QSize(50, 0))
        self.stones.setMaximumSize(QtCore.QSize(50, 16777215))
        self.stones.setMinimum(3)
        self.stones.setMaximum(6)
        self.stones.setProperty("value", 3)
        self.stones.setObjectName("stones")
        self.gridLayout_3.addWidget(self.stones, 0, 2, 1, 1)
        self.timing_box = QtWidgets.QGroupBox(kalah_options)
        self.timing_box.setGeometry(QtCore.QRect(10, 170, 221, 79))
        self.timing_box.setObjectName("timing_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.timing_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.timer_on = QtWidgets.QCheckBox(self.timing_box)
        self.timer_on.setObjectName("timer_on")
        self.gridLayout_2.addWidget(self.timer_on, 0, 0, 1, 1)
        self.time_per_move_label = QtWidgets.QLabel(self.timing_box)
        self.time_per_move_label.setObjectName("time_per_move_label")
        self.gridLayout_2.addWidget(self.time_per_move_label, 1, 0, 1, 1)
        self.time_per_move = QtWidgets.QSpinBox(self.timing_box)
        self.time_per_move.setMinimumSize(QtCore.QSize(50, 0))
        self.time_per_move.setObjectName("time_per_move")
        self.gridLayout_2.addWidget(self.time_per_move, 1, 1, 1, 1)
        self.visualization_box = QtWidgets.QGroupBox(kalah_options)
        self.visualization_box.setGeometry(QtCore.QRect(10, 260, 221, 53))
        self.visualization_box.setObjectName("visualization_box")
        self.gridLayout = QtWidgets.QGridLayout(self.visualization_box)
        self.gridLayout.setObjectName("gridLayout")
        self.show_moves = QtWidgets.QCheckBox(self.visualization_box)
        self.show_moves.setObjectName("show_moves")
        self.gridLayout.addWidget(self.show_moves, 0, 0, 1, 1)

        self.retranslateUi(kalah_options)
        self.buttonBox.accepted.connect(kalah_options.accept)
        self.buttonBox.rejected.connect(kalah_options.reject)
        QtCore.QMetaObject.connectSlotsByName(kalah_options)

    def retranslateUi(self, kalah_options):
        kalah_options.setWindowTitle(QtCore.QCoreApplication.translate("kalah_options", "Dialog", None))
        self.gameplay_box.setTitle(QtCore.QCoreApplication.translate("kalah_options", "Gameplay", None))
        self.label_2.setText(QtCore.QCoreApplication.translate("kalah_options", "Stones:", None))
        self.ai_level_label_2.setText(QtCore.QCoreApplication.translate("kalah_options", "AI level:", None))
        self.ai_level_label_1.setText(QtCore.QCoreApplication.translate("kalah_options", "AI level:", None))
        self.label_3.setText(QtCore.QCoreApplication.translate("kalah_options", "Player 2:", None))
        self.label.setText(QtCore.QCoreApplication.translate("kalah_options", "Player 1:", None))
        self.timing_box.setTitle(QtCore.QCoreApplication.translate("kalah_options", "Timing", None))
        self.timer_on.setText(QtCore.QCoreApplication.translate("kalah_options", "Timer ON", None))
        self.time_per_move_label.setText(QtCore.QCoreApplication.translate("kalah_options", "Timer per move, sec:", None))
        self.visualization_box.setTitle(QtCore.QCoreApplication.translate("kalah_options", "Visualization", None))
        self.show_moves.setText(QtCore.QCoreApplication.translate("kalah_options", "Show moves", None))

